on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    strategy:
      matrix:
        include:
          - board: seeeduino_xiao_ble
            shield: my38key_left
          - board: seeeduino_xiao_ble
            shield: my38key_right
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Build (${{ matrix.shield }})
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="$GITHUB_WORKSPACE/config"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 ${{ matrix.shield }}-${{ matrix.board }}.uf2
      - name: Archive (${{ matrix.shield }})
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}
          path: ${{ matrix.shield }}-${{ matrix.board }}.uf2
